### ISSUE TITLE
Ubuntu MATE + RPi3

### ISSUE THREAD

**Issue by regisin** [seemoo-lab/nexmon#10]
I am currently looking for a way to use Raspberry Pi 3 Mobel B with the built-in Broadcom wifi chip in promiscuous mode. I HAVE to use Ubuntu MATE (not raspbian), as I will be using some tools that only work on that OS. Before I venture myself on testing nexmon, I'd like to know if any of you have tried it before. Or any idea if it might work or not?

Thank you

**Comment by matthiasseemoo** [comment]
We did not try it on Ubuntu MATE, however, you should still be able to follow the instructions to compile the driver as well as the firmware patch as described in our README. Let us know, if it works.

**Comment by DanielAW** [comment]
No new info, closed for now
