### ISSUE TITLE
Support RPi 3 64-bit (aarch64) distros

### ISSUE THREAD

**Issue by sHAsHiLx** [seemoo-lab/nexmon#104]
Is there any way in future to support aarch64 linux distros?

**Comment by matthiasseemoo** [comment]
Why not? It is an open source project, so just add support for aarch64 and
send us a pull request.

Am 21.07.2017 7:46 nachm. schrieb "Roman Papusha" <notifications@github.com

**Comment by sHAsHiLx** [comment]
I can't because don't have enough knowledge ) My question is - will you? )

**Comment by matthiasseemoo** [comment]
No, I don't have the time and do not need it myself.

Am 25.07.2017 12:08 nachm. schrieb "Roman Papusha" <notifications@github.com

**Comment by sHAsHiLx** [comment]
Are you developer/committer of the project?

**Comment by matthiasseemoo** [comment]
Just look into the commit history.
