### ISSUE TITLE
nexutil: command not found

### ISSUE THREAD

**Issue by denverpi3B** [seemoo-lab/nexmon#105]
Hey, 

I get this error when trying to change modes with nexmon -m2 or nexmon -m0.

What is wrong?

**Comment by bakashinji** [comment]
'nexutil -m2' not 'nexmon'

**Comment by denverpi3B** [comment]
Sorry. Typo. The error appears when using "nexutil -m2" or "nexutil -m0". I was distracted by the folder name.

**Comment by bakashinji** [comment]
see #35 then

**Comment by denverpi3B** [comment]
Yes - it fixed it! BUT now… I am not able to connect to access points in managed mode. "nexutil -m0" brings me back to managed mode but I can not connect to access points, as it always says: No wireless interfaces found. 

wpa_supplicant.conf seems to have all the relevant and right data.

**Comment by bakashinji** [comment]
ifconfig wlan0 up should fix that you have no interface

**Comment by Borduni** [comment]
This issue could be closed
