### ISSUE TITLE
Wlan managed, but no internet

### ISSUE THREAD

**Issue by djangoary** [seemoo-lab/nexmon#106]
Everything works fine. Changing from monitor mode to managed works as well. SSH works, but I can not connect to the internet to download and install apps. 

What could be the problem here?

**Comment by KenHayChung** [comment]
Don't know what device or OS you are using but I got the same problem with my pi zero W before. In my case I just load the original driver.

rmmod brcmfmac
modprobe brcmfmac

hope this help.

**Comment by matthiasseemoo** [comment]
Unfortunately, we start the brcmfmac driver with the wrong interface type. Even though monitor mode is deactivated in the firmware, the interface shows up as radiotap interface. Simply run "nexutil -m0" and you can access regular accesspoints in station mode.
