### ISSUE TITLE
Error with RPI3 install instructions

### ISSUE THREAD

**Issue by cyberintelpro** [seemoo-lab/nexmon#113]
Reads...Copy the modified driver: cp /home/pi/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/brcmfmac.ko "<PATH TO THE DRIVER>/"

should read 
```bash
 
cp /home/pi/nexmon/patches/bcm43430a1/7_45_41_46/nexmon/brcmfmac_kernel49/brcmfmac.ko "/lib/modules/4.9.41-v7+/kernel/drivers/net/wireless/broadcom/brcm80211/brcmfmac/"

```

**Comment by cyberintelpro** [comment]
this one worked
```bash
 
cp /home/pi/nexmon/patches/bcm43430a1/7_45_41_46/nexmon/brcmfmac_kernel49/brcmfmac.ko "/lib/modules/4.9.41-v7+/kernel/drivers/net/wireless/broadcom/brcm80211/brcmfmac/"

```

**Comment by SilverLeo** [comment]
I also ran into this issue. I copied the wrong file from the wrong folder in /home/pi/nexmon/patches/ and at boot time /var/log/messages will show this error and you will not get the wlan0 interface at all.

`kernel: [    6.860138] brcmfmac: disagrees about version of symbol module_layout`

Once you copy over the correct file, it works. Thanks @cyberintelpro for the correct path.
