### ISSUE TITLE
Nexus 6p

### ISSUE THREAD

**Issue by akhmed2001** [seemoo-lab/nexmon#118]
While iam trying to install tools from your app ( like nexutil) its writing "Cant install to /system/bin/"tool name" ". how to fix it ?

**Comment by akhmed2001** [comment]
Sry, my bad, i didnt know how to change path of instalation

**Comment by matthiasseemoo** [comment]
I think it is a problem with the default mount binary. try to remount your
system partition as writable and then use the app. with the current
development version you can build from our repository, you do not even need
to install any tools.

Am 15.09.2017 8:12 nachm. schrieb "akhmed2001" <notifications@github.com>:
