### ISSUE TITLE
Nexus 5 : Linage OS 14.1

### ISSUE THREAD

**Issue by DarrenRainey** [seemoo-lab/nexmon#132]
Just wanted to say that I can confirm that the firmware works on the Nexus 5 running linage os 14.1 (Android Nogut)

**Comment by BearChavez** [comment]
I honestly am not sure where to ask and I'm sure this is the wrong place, but why isn't the Nexus 5X being worked on? Is it just not something people are looking in to or is it because of the chipset?

**Comment by matthiasseemoo** [comment]
because it is a qualcomm chipset, but feel free to work on it.

Am 18.10.2017 8:44 nachm. schrieb "BearChavez" <notifications@github.com>:

**Comment by BearChavez** [comment]
@matthiasseemoo How would I begin working on that?
