### ISSUE TITLE
is there a list of all phones with broadcom chipsets?

### ISSUE THREAD

**Issue by chrisdroid** [seemoo-lab/nexmon#145]
On gsmarena.com for example there is a list of popular phones. Is there a way to know which wifi chipset is used on each phone?
```
Samsung Galaxy S8
Sony Xperia XZ Premium
OnePlus 3T
OnePlus 5
Samsung Galaxy S8+
Xiaomi Mi Mix
Nokia 8
Samsung Galaxy Note8
LG V20
LG G6
```

**Comment by matthiasseemoo** [comment]
run nexutil -V to get the revision information in case you have a broadcom
chip. then you can add it to our REVINFO.md file.

Am 02.11.2017 5:26 nachm. schrieb "Chris" <notifications@github.com>:

**Comment by kimocoder** [comment]
Sony Xperia Z5 E6653
Huawei Nexus 6P
