### ISSUE TITLE
undefined reference to `ucode_compressed_bin_len'

### ISSUE THREAD

**Issue by RenaKunisaki** [seemoo-lab/nexmon#146]
Attempting to build `bcm43430a1/7_45_41_46` patch on Pi 3 on Arch Linux fails:

```
obj/ucode_compression_code.o: In function `wlc_ucode_write_compressed':
ucode_compression_code.c:(.text.wlc_ucode_write_compressed+0x40): undefined reference to `ucode_compressed_bin_len'
ucode_compression_code.c:(.text.wlc_ucode_write_compressed+0x50): undefined reference to `ucode_compressed_bin'
```

**Comment by matthiasseemoo** [comment]
did you run make in the repo's root directory?

Am 05.11.2017 9:14 nachm. schrieb "Rena Kunisaki" <notifications@github.com

**Comment by RenaKunisaki** [comment]
Ah, I missed that step.

Now it gets to building the driver but fails because `/usr/lib/modules/4.9.60-1-ARCH/build` doesn't exist. (Also I had to change `b43/assembler/Makefile` to use `lfl` instead of `ll`.)

**Comment by matthiasseemoo** [comment]
Unfortunately, we do not officially support Arch Linux, so you need to cope with the compilation errors on your own.

**Comment by RenaKunisaki** [comment]
Could I build it on Raspbian but use it on Arch? Would it work? Would I need to copy some files over or is the firmware stored on-chip?

**Comment by DanielAW** [comment]
I don't think that this will work. Because we compile the kernel driver ourself. The kernel module needs to match with the used kernel version. You will be unable to load the kernel module in Arch because the kernel versions dont match (Arch most likely uses a newer Kernel version).
