### ISSUE TITLE
How to restore original wifi driver

### ISSUE THREAD

**Issue by jmanuelnavarro** [seemoo-lab/nexmon#16]
Nexmon is a great project but, how can I restore original driver in my raspberry Pi?
Thanks in advance

**Comment by DanielAW** [comment]
We do not replace the original driver in `/lib/modules/`. This means that a simple `rmmod brcmfmac` and `modprobe brcmfmac` should load the original driver (modprobe looks for .ko files in `/lib/modules/`). Rebooting the RPI should also work.
But remember: You also need to restore the originail firmware file from your nexmon directory:
```cp patches/bcm43438/7_45_41_26/nexmon/brcmfmac43430-sdio.bin.orig /lib/firmware/brcm/brcmfmac43430-sdio.bin
```

**Comment by jmanuelnavarro** [comment]
It worked!
Thanks a lot
