### ISSUE TITLE
Cannot control sequence number and duration field in packet injection

### ISSUE THREAD

**Issue by zjlywjh001** [seemoo-lab/nexmon#202]
I'm trying to use nexmon to inject fake data frame in my network. But I found that my STA cannot receive my fake frame.I must send the same frame fast for about hundredes of times before the sta can receive one.
After some analysis, I found that whatever the sequence number of the raw packet is, the sequence number  packet transmitted over the air always be started from 1. 
For example, When I send qos data like the following:
8842c000701ce7446bafe03f49ec9568001122334456**f0ff**0000610100200000000082a78017b97fece9d7c6b5aa76942f5613e5c63cdd33bb3cb7a3a70b78681f4e8fc93d5a4c7b0c61ab2dda45c5bbd688fe83f39ce1f61265f98c1e5046b3e12ada2c8830c938d13fbf1e26466313685568210a5106e301a1c2450f030b584d33004c45e8dafdac3b
the SN of the packet is 4095

But the acture frame I captured is:
8842c000701ce7446bafe03f49ec9568001122334456**1000**0000610100200000000082a78017b97fece9d7c6b5aa76942f5613e5c63cdd33bb3cb7a3a70b78681f4e8fc93d5a4c7b0c61ab2dda45c5bbd688fe83f39ce1f61265f98c1e5046b3e12ada2c8830c938d13fbf1e26466313685568210a5106e301a1c2450f030b584d33004c45e8dafdac3b

the SN of the packet over the air is modified to 1。

I send frame use **wlc_sendctl** function

Is the sequence number are controlled by the even lower level of the chip(maybe D11 core)? Can I make a patch to let this field controlled by myself?

**Comment by matthiasseemoo** [comment]
Currently the sequrnce number is set automatically. It might be sufficient
to fisable this in the d11 tx header by changing a flag. Otherwise you have
to do it in the d11 core.

Jarvis <notifications@github.com> schrieb am Mo., 2. Apr. 2018, 10:57:

**Comment by zjlywjh001** [comment]
Are there more details of the instruction set of d11? I can't find any explanation of the b43 architecture, how can I patch it?

**Comment by matthiasseemoo** [comment]
Read our papers and the makefiles. Here is a specification:
https://bcm-v4.sipsolutions.net/

Jarvis <notifications@github.com> schrieb am Di., 3. Apr. 2018, 14:00:

**Comment by zjlywjh001** [comment]
finally I have to patch d11 microcode ,and made sequence number controlled by myself.

**Comment by Guohua-Sun** [comment]
Hi

How do you control the sequence number controlled by yourself. Could you share your code that you changed? I know little about d11 core. Thanks.
@zjlywjh001
