### ISSUE TITLE
Please add support for kernel 4.14 on Raspberry Pi

### ISSUE THREAD

**Issue by yydcool** [seemoo-lab/nexmon#203]
The kernel version in Raspbian Stretch is updated to 4.14 as of 20180328. 
I follow the steps to 

> cd patches/bcm43430a1/7_45_41_46/nexmon/
make

It can not compile the driver here.

**Comment by matthiasseemoo** [comment]
4.14 is now supported.

**Comment by dschoonwinkel** [comment]
I have successfully installed nexmon on 4.14.30-v7+, but wlan0 disappears as soon as make install-firmware completes. 
sudo ifconfig wlan0 up and sudo ip link set dev wlan0 up also does not bring back wlan0. Thus, you cannot add a monitor to a interface which is not there...

**Comment by skoehler** [comment]
How is 4.14 supported? The `patches/bcm43430a1/7_45_41_46/nexmon` folder does not yet contain a subfolder for 4.14. I'm trying to get nexmon working on a Raspberry Pi 3 B (not B+). And I assume I have to use `bcm43430a1`, right? The original reporter (yydcool) seems to be also using a Pi 3 B (not B+) and also asks for 4.14 support in the `bcm43430a1` subfolder.

I see that there is a 4.14 subfolder in the `bcm43455c0` subdirectory, but that's only for the new Raspberry Pi 3 B+, AFAIK.

**Comment by skoehler** [comment]
I cannot recommend the downgrade method described by yydcool. Just grab the last 4.9.x kernel and headers from the official Raspbian repository. Version 1.20170811-1 corresponds to kernel 4.9.80.
http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/

**Comment by jgamos** [comment]
> I cannot recommend the downgrade method described by yydcool. Just grab the last 4.9.x kernel and headers from the official Raspbian repository. Version 1.20170811-1 corresponds to kernel 4.9.80.
> http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/

how do you perform this? im sorry for asking, i dont know how to.
