### ISSUE TITLE
NexMon with Nexus 5 not working

### ISSUE THREAD

**Issue by AutinDroid** [seemoo-lab/nexmon#23]
I saw with a new update that NexMon says that the firmware is incompatible with my cm14.1 nexus 5. I can prove this is false, as in previous versions, the app would install it, and it would work in chroot.

**Comment by FabianKnapp** [comment]
Thank you for sharing this information with us!
Could you tell us the path in which the fw_bcmdhd.bin lives?

Are you sure that nexutil is installed properly with the correct version as proposed in the app?
