### ISSUE TITLE
make install-firmware is stuck

### ISSUE THREAD

**Issue by hplinarian** [seemoo-lab/nexmon#248]
COPYING /sdcard/fw_bcmdhd.bin => /vendor/firmware/fw_bcmdhd.bin
rm ro /vendor/firmware/fw_bcmdhd.bin (y/N):

It shows no response no matter what I type

**Comment by hplinarian** [comment]
solved after remount /vendor as rw

**Comment by mirzaatifbaig** [comment]
Close this issue.
