### ISSUE TITLE
Installation on Raspbian

### ISSUE THREAD

**Issue by xxluke** [seemoo-lab/nexmon#257]
Hi,

I'm trying to use Monitor Mode on my Raspberri Pi B+ with the current Raspbian (9) and because it doesn't work by default I tried it with this project.

I followed the instructions from the readme, but when starting `./configure` I get an error:
```
root@raspberrypi:~/nexmon/buildtools/isl-0.10# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... /root/nexmon/buildtools/gcc-arm-none-eabi-5_4-2016q2-linux-armv7l/bin/arm-none-eabi-
checking whether the C compiler works... no
configure: error: in `/root/nexmon/buildtools/isl-0.10':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

I don't know if it's relevant that I first tried it without compiling `libisl.so.10` (because I thought `libisl.so.15` would be fine too; sry), but I deleted and re-downloaded the nexmon-dir afterwards.

Unfortunally, I'm a noob at unix.
I hope you can help!

**Comment by BennyE** [comment]
Please try again after

$ sudo apt install libc6-dev

**Comment by BennyE** [comment]
.. did you do **source setup_env.sh** before you tried to compile **isl-0.10**? If yes, this was not correct. You need to compile isl-0.10 _before_ you do "source setup_env.sh".

**Comment by MaximusBaton** [comment]
I could not make it work on Raspberry Pi 3B+ (armv7l) so far. Even with successful command executions.
However the same steps make the monitor mode working on Zero W (armv6l)

**Comment by MaximusBaton** [comment]
Not sure if B+ is the same as 3B+.
For Raspi 3B+ or Zero W, I made it working: https://github.com/seemoo-lab/nexmon/issues/259#issuecomment-438768001

**Comment by xxluke** [comment]
I completly started from the beginning by flashing a new raspbian, that worked.
