### ISSUE TITLE
Devices.md possible mistake

### ISSUE THREAD

**Issue by chrisk44** [seemoo-lab/nexmon#276]
I see you have listed LG G2 as BCM4335 in [DEVICES.md](https://github.com/seemoo-lab/nexmon/blob/master/DEVICES.md), but it has the MSM8974 chipset, same as Nexus 5. Maybe it should be under BCM4339?

**Comment by mirzaatifbaig** [comment]
I don't know maybe,but you can check the kernel defconfig for confirmation.

**Comment by chrisk44** [comment]
Alright, I opened a [pull request](https://github.com/seemoo-lab/nexmon/pull/277).
