### ISSUE TITLE
Raspberry pi zero W

### ISSUE THREAD

**Issue by gudata** [seemoo-lab/nexmon#289]
Hello,
I can't capture packets with kernel  4.14.98+, there was no problem with  4.14.79+.
There are no errors or warnings. Just no packets.

**Comment by DrSchottky** [comment]
Same setup, works for me.

**Comment by gudata** [comment]
It worked for me also. 

I suspect that I have compiled the isl library with the old kernel.

When I start from the clean repo and follow *all* step it works.
