### ISSUE TITLE
S8+ bcm4361_b0 __nex_driver_io: error

### ISSUE THREAD

**Issue by Coding-Cyanide** [seemoo-lab/nexmon#293]
Im sorry, im short on time right now... here is what i have for you:

If I try to run source setup_env.sh I get a error: "Platform not supported!"

Any help please!!! I really want monitor mode!
Thanks so much, I really appreciate you!
Cyanide

**Comment by matthiasseemoo** [comment]
What is your buildsystem? Did you follow all instructions from the readme?

Coding-Cyanide <notifications@github.com> schrieb am Fr., 15. März 2019,
00:08:

**Comment by Coding-Cyanide** [comment]
What do you mean by buildsystem and yes, I followed the read me carefully

**Comment by matthiasseemoo** [comment]
Which ubuntu version on which processor? Did you grep for the erreo message
in the build files to figure out where it is generated?

Coding-Cyanide <notifications@github.com> schrieb am Fr., 15. März 2019,
14:29:

**Comment by Coding-Cyanide** [comment]
Linux version 4.4.16-12542406
Processor msm8998

No I didn't I'm new to this so bear with me. :)

Thanks so much!!

**Comment by matthiasseemoo** [comment]
I meant the processor of your buildsystem. However, it will not be a quick
solution and monitor mode support for the s8 is currently only
experimental. So you will need some time to get it running and understand
how it works.

Coding-Cyanide <notifications@github.com> schrieb am Fr., 15. März 2019,
18:27:

**Comment by Coding-Cyanide** [comment]
Can I get some help through the process? I really appreciate your help!

**Comment by Coding-Cyanide** [comment]
Bump (sorry I'm very impatient)

**Comment by Coding-Cyanide** [comment]
Bump
