### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by seyo-IV** [seemoo-lab/nexmon#300]
root@kali:~/nexmon/patches/bcm4358/7_112_300_14_sta/nexmon/# make

COLLECTING STATISTICS read /root/nexmon/STATISTICS.md for more information
  COMPILING src/ioctl.c => obj/ioctl.o (details: log/compiler.log)
/bin/sh: 1: /root/nexmon/buildtools/gcc-arm-none-eabi-5_4-2016q2-osx/bin/arm-none-eabi-gcc: Exec format error
make: *** [Makefile:46: obj/ioctl.o] Error 2

Error Log says:
gen/nexmon.pre: No such file or directory

Im trying to Install nexmon in a Nexus 6p Oreo. My distribution ist kali.
I've tried with the app(version 2.1.3) no success. When i try /system/bin/nexutil -m2 wlan0 stay managed.

**Comment by seyo-IV** [comment]
As mentioned I managed to install the nexmon app. No I have the problem that I can't install the nexutil and proxy. Even tho my system is writable... Strange is it worked on Oreo 8.1.1 but doesn't on 8.0.0.

On 8.1.1 I couldn't get the monitor mode working properly. So many problems...

**Comment by seyo-IV** [comment]
Tried the same on a PC running Ubuntu. Same error: gen/nexmon.pre: No such file or directory

**Comment by matthiasseemoo** [comment]
Which processor architecture do you have on your pc?

Ivanov <notifications@github.com> schrieb am Mi., 24. Apr. 2019, 16:15:

**Comment by seyo-IV** [comment]
Can someone provide me the binary for bcm4358
7.112.200.17 so I have to just run make install firmware

**Comment by seyo-IV** [comment]
I got a x86_64

**Comment by Intelectus-mss** [comment]
error: 
   REMOUTING /vendor
mount: '/vedor' not in /proc/mounts
make: *** [Makefile:163: install-firmware] Error 1

on Nexus 6 Linegeos 16
