### ISSUE TITLE
Can't install untils in any directory

### ISSUE THREAD

**Issue by seyo-IV** [seemoo-lab/nexmon#301]
I'm trying to install nexutil on a Nexus 6p Oreo stock. But I can't. I have already mounted system as rw but it didn't help.
It's strange cuz it worked flawlessly on Android 8.1.0 but there I couldn't activate monitor mode.

**Comment by seyo-IV** [comment]
Can someone provide the libs and bins?
Only nexutil, rawproxyreverse, rawproxy and libfakeioctl. Plz

**Comment by Coding-Cyanide** [comment]
When I get home I'll provide those tools! I don't have access to my Linux ATM. Ill be home around 4:00 P.M. PST... See you then!

Cyanide

**Comment by Coding-Cyanide** [comment]
Scratch that it'll probably be more like 6:00 PM PST

**Comment by seyo-IV** [comment]
Well I have to wait then. But better than nothing I guess😅

**Comment by Coding-Cyanide** [comment]
> Can someone provide the libs and bins?
> Only nexutil, rawproxyreverse, rawproxy and libfakeioctl. Plz

Sorry for the extremely late reply. I got extremely busy and wasn't able to use Linux at the time.
There was a 64 bit and 32 bit nexutil, I built both of them for you although I believe your phone is 64 bit. Just in case though the 3
[seyo-IV-nexmon-tools.zip](https://github.com/seemoo-lab/nexmon/files/3133503/seyo-IV-nexmon-tools.zip)
2 bit is named 'nexutil32' and the 64 bit is called 'nexutil64', rename the one you need to 'nexutil'. If the 64 bit version or the 32 bit version doesn't work, try to use the other version. If that doesn't work... Honestly, I have no clue.

In the case you didn't know:
All files in the zip that have the .'so' (shared library) extension go to /system/lib
All files in the zip that have no extension go to /system/bin (I believe this is the default) or /system/sbin or /system/xbin


If anything is inaccurate, let me know!
Good luck and enjoy!

~Cyanide

**Comment by seyo-IV** [comment]
Thanks mate :)

**Comment by seyo-IV** [comment]
Just a Tipp if someone else need this make: chmod +x so the tools are executable

**Comment by seyo-IV** [comment]
Can you also provide the iwconfig tools I'm having trouble setting the monitor mode from the Kali shell. And I can't use iwconfig outside the Kali shell. So just to test if monitor mode does really work I need these tools. If it works I would need all the rest of the tools. I hope don't ask for too much.

**Comment by Coding-Cyanide** [comment]
Sure, I will be home soon.

~Cyanide

**Comment by seyo-IV** [comment]
dude u forget about me?^^

**Comment by Coding-Cyanide** [comment]
Sorry, i have been extremely busy lately...ill let you know shen i have iwconfig!

**Comment by seyo-IV** [comment]
@matthiasseemoo what im doing wrong? I have installed the patch and the tools. The tool were installed manualy. When i use nexutil -m2 wlan0 stays in mode mnaged. What am i missing?

**Comment by matthiasseemoo** [comment]
Libnexmon.so?

Ivanov <notifications@github.com> schrieb am Di., 21. Mai 2019, 09:21:

**Comment by seyo-IV** [comment]
no i have only the old libfakeioctl.so. Since i couldn't install the tools from the app i had to rely on other people providing me the tools.

**Comment by seyo-IV** [comment]
@matthiasseemoo hi, there its me again, i have build the tools myself where are they located after i run make?

**Comment by matthiasseemoo** [comment]
You can always take a look into the Makefiles of the tools. There you find
the path of the built binaries. There is also a make install command that
installs the tools on your smartphone.

For example:
https://github.com/seemoo-lab/nexmon/blob/master/utilities/dhdutil/Makefile

Ivanov <notifications@github.com> schrieb am Di., 21. Mai 2019, 16:01:

**Comment by seyo-IV** [comment]
okay, I managed to install the tools with a Linux machine and NDK installed.
