### ISSUE TITLE
Nexus 6P Android 8 stock can't activate monitor mode

### ISSUE THREAD

**Issue by seyo-IV** [seemoo-lab/nexmon#308]
I have nexmon firmware and tool installed on my nexus 6P.
When i do nexutil -m2, iwconfig say wlan0 is still managed.
When i do export LD_PRELOAD=libnexmon.so and try to use airodump, for example, it says couldn't set monitor mode for wlan0.

I did everything that was in the instructions and it still doesn't work....

**Comment by felbutss** [comment]
I send that..

**Comment by seyo-IV** [comment]
I finally managed to get it working. Somehow when I do nexutil -m2 wlan0 seems to be in managed mode, but it is not. when I run LD_PRELOAD=libfakeioctl.so airodump -i wlan0 it did work. But this doesn't work in the kali shell. but does in android su shell.

**Comment by yesimxev** [comment]
As for NH terminal, you should do `export LD_PRELOAD=/system/lib64/kalilibfakeioctl.so`, but that's included in monstart-nh
