### ISSUE TITLE
New Cypress FMAC Driver/FW release

### ISSUE THREAD

**Issue by DrSchottky** [seemoo-lab/nexmon#346]
https://community.cypress.com/docs/DOC-17441

43430 bumped to version  7.45.98.94
43455 43430 bumped to version 7.45.197

**Comment by TJFJefroy** [comment]
are there any guides on how to add this firmware to nexmon?

**Comment by DrSchottky** [comment]
No, you need to change addresses/offests in

- definitions.mk
- firmware_version.h
- wrapper.c
- nexmon/src/*

according to the new values that you can extract by manually analyzing fw
