### ISSUE TITLE
Nexmon monitor wont run

### ISSUE THREAD

**Issue by TFM110** [seemoo-lab/nexmon#347]
Whenever i try to run this on my Raspberry Pi Zero W, `sudo iw phy `iw dev wlan0 info | gawk '/wiphy/ {printf "phy" $2}'` interface add mon0 type monitor`, It keep on giving me this error: `Command failed: No such device (-19)` and `Command failed: No such file or director (-2)`.
How do i fix this?

**Comment by Pablichenco** [comment]
I have the same problem :/
