### ISSUE TITLE
bcm43455 no any capture

### ISSUE THREAD

**Issue by Gorkem63** [seemoo-lab/nexmon#354]
my device sony xperia Z5 Compact i compiled the 7_45_77_0_hw_23_8_2017
firmware. its ok then i installed nexmon apk and go to tools and activated and installed all no any errors.
(nexmon play store version)
after go terminal and nexutil -m2
no issue but when i type airodump-ng wlan0 error it say no monitor mode supported! : operation not supported on transport endpoint
ioctl(SI0CSIWMODE) failed: operation not supported on transport endpoint
error setting monitor mode on wlan0
also i got nothing packets in nexmon airodump.
![Screenshot_20191206-153959](https://user-images.githubusercontent.com/52033039/70323774-c3308f80-183e-11ea-803a-4c17bbe188fa.png)
![Screenshot_20191206-154009](https://user-images.githubusercontent.com/52033039/70323789-ccb9f780-183e-11ea-8675-dbe5390e75b7.png)
![Screenshot_20191206-154141](https://user-images.githubusercontent.com/52033039/70323911-2de1cb00-183f-11ea-93df-6d6e7f41f915.png)

**Comment by Gorkem63** [comment]
@baselsayeh @matthiasseemoo

**Comment by baselsayeh** [comment]
You need to compile and use libnexmon

**Comment by Gorkem63** [comment]
> You need to compile and use libnexmon

compile the nexmon app right?
can you say instructions :)
i ill subscribe you dudedee :)

**Comment by baselsayeh** [comment]
Compile it, then use
LD_PRELOAD=libnexmon.so airodump-ng wlan0
After setting the monitor mode
nexutil -m2
And you maybe need to disable scanning by
nexutil -c1
nexutil -d

**Comment by Gorkem63** [comment]
> Compile it, then use
> LD_PRELOAD=libnexmon.so airodump-ng wlan0
> After setting the monitor mode
> nexutil -m2
> And you maybe need to disable scanning by
> nexutil -c1
> nexutil -d

by saying you compile is, fw or app?
i complieded fw already bro
just wanna know to how compile app

**Comment by Gorkem63** [comment]
@matthiasseemoo @baselsayeh i need to learn compile nexmon apk for my z5c bcm43455 (i already compiled fw and installed)
with nexmon i planning mdk3, airodump (i also have nethunter kali so i prefer kali aircrack #:) )

**Comment by matthiasseemoo** [comment]
We did not maintain the app since a long time. Normally, the existing
version of the app should work. If not, you need to compile it using the
exact versions of the tools provided in the readme.

Gorkem63 <notifications@github.com> schrieb am Fr., 6. Dez. 2019, 16:54:

**Comment by Gorkem63** [comment]
fixed thanks :)
