### ISSUE TITLE
How can i run nexmon in nethunter chroot

### ISSUE THREAD

**Issue by SamuelNigga** [seemoo-lab/nexmon#356]
compiled and succesfully run in android but when mdk deauth attack, phone freeze .is it my compile problem?

so possible to build in chroot ?
@baselsayeh :)

also in every terminal open, am i must the write LD_PRELOAD=libnexmon.so ?
because if i doesnt execute this command, i dont get monitor

**Comment by baselsayeh** [comment]
@Gorkem63 
Is it the whole phone, or the Wi-Fi chip only?
If you inject too much packets, the Wi-Fi chip will run out of ram, and it will crash
try lowering the number of packets in aireplay-ng
e.g:
`aireplay-ng -0 1`
Or
`aireplay-ng -0 2`


And for the LD_PRELOAD, yes you need that, as the nexmon modified firmware's injection (And monitoring) method is not standard, and do not have the drivers in linux
However, you can export the LD_PRELOAD variable, and use airodump/aireplay
```
LD_PRELOAD=libnexmon.so
export LD_PRELOAD
airodump-ng ...

```

**Comment by SamuelNigga** [comment]
@baselsayeh the whole phone is my prefer
so i wanna set up mon0 mode:
`airmon-ng start wlan0
for the use nethunter kali tools.

**Comment by SamuelNigga** [comment]
i got export is not an identifier while type:
`export LD_PRELOAD`

**Comment by baselsayeh** [comment]
@SamuelNigga 
I really do not know anything about kali nethunter.
And if you are using nexmon firmware, there is no need for airmon-ng, you should read [README.MD](https://github.com/seemoo-lab/nexmon/blob/master/README.md) to set it up.

**Comment by SamuelNigga** [comment]
![IMG_20191207_193253](https://user-images.githubusercontent.com/52033039/70377701-86d95e00-1928-11ea-9cb2-7911996d766e.jpg)

![IMG_20191207_193320](https://user-images.githubusercontent.com/52033039/70377707-9658a700-1928-11ea-8ce2-540b50579616.jpg)

in nethunter @baselsayeh

**Comment by SamuelNigga** [comment]
now got this:
![IMG_20191207_195755](https://user-images.githubusercontent.com/52033039/70377966-ec7b1980-192b-11ea-909f-a6f776d8d153.jpg)

**Comment by baselsayeh** [comment]
It tells you you have the one with wrong architecture of libnexmon.so.
Either compile or download libnexmon.so first

As i said, i don't know anything about kali, i might not be very helpful here, sorry

**Comment by SamuelNigga** [comment]
> It tells you you have the one with wrong architecture of libnexmon.so.
> Either compile or download libnexmon.so first
> 
> As i said, i don't know anything about kali, i might not be very helpful here, sorry

oww ok, nethunter's architecture is aarch64 you gave me for the android main arm64 libs so thats way it dont work in nethunter.
if i compile utilities in nethunter  chroot? is it run ? :)

**Comment by baselsayeh** [comment]
@SamuelNigga 
Ok, i dont know if anything will compile under kali.
[Read this](https://github.com/seemoo-lab/nexmon/issues/355#issuecomment-562761545) steps, and you might need to replace the /system paths with your chroot pathes

**Comment by SamuelNigga** [comment]
thanks @baselsayeh
