### ISSUE TITLE
cant add mon0 interface

### ISSUE THREAD

**Issue by SamuelNigga** [seemoo-lab/nexmon#357]
`iw phy phy0 interface add mon0 type monitor`
command failed: Operation not supported on transport endpoint (-95)
@baselsayeh @matthiasseemoo 
the wlan0 airodump and mdk3 is working very well, i want to add mon0 interface but errors run.

![IMG_20191207_203934](https://user-images.githubusercontent.com/52033039/70378472-c2c4f100-1931-11ea-82cc-5a75c5615379.jpg)

**Comment by SamuelNigga** [comment]
i think the iw isnt compiled my device, thats way i got errors
@baselsayeh can you compile all  nexmon utilities for my device (arm64)  ?
:)

**Comment by baselsayeh** [comment]
@SamuelNigga 
Please do read the README.md, as everything is explained there.
You do not need the mon0 interface (this is not how nexmon works), You just need:
```
LD_PRELOAD=libnexmon.so
export LD_PRELOAD
nexutil -c1
nexutil -d
nexutil -m2
airodump-ng wlan0

```

But as i said, it may or may not work under kali, as i do not know anything about it.
