### ISSUE TITLE
Building APK

### ISSUE THREAD

**Issue by SamuelNigga** [seemoo-lab/nexmon#362]
i want learn the Building apk instructions.
need to build nexmon apk.
@baselsayeh @matthiasseemoo

**Comment by kimocoder** [comment]
Clone the project, load it in Android Studio and "Build APK" ..

**Comment by SamuelNigga** [comment]
@kimocoder so dont need to enter nexmon after patch firmware then downliad ndk, set NDK_ROOT=ndk directory after make utilities ?

**Comment by kimocoder** [comment]
When building utilities you need the NDK_ROOT path yes. And used the older toolchain, described in the README.md :+1:

**Comment by SamuelNigga** [comment]
@kimocoder bro my device arm64, so when i will build apk (like you said(clone nexmon, install android studio))  and  install my phone it will install utilities (aircrack) for my phone's arch right? also am i will succesfully run wireshark in builded nexmon app right ?

**Comment by kimocoder** [comment]
You need to install the utilities from the app itself.
But remember.. Nexmon is a bit outdated sort og, so it may need some developer "skills" in order to make it all work, depending on device, versions etc.. the easiest for you would be to use the Nexmon APK v2.1.3 found online.

**Comment by SamuelNigga** [comment]
@kimocoder ok bro, cloning project and dowloading AS, after i will open and install AS then open nexmon folder and clicking build apk.Ok thanks bro :)
