### ISSUE TITLE
What are 'Cores'?

### ISSUE THREAD

**Issue by zeroby0** [seemoo-lab/nexmon#373]
Help section of makecsiparams shows this
```
   -C coremask  bitmask with cores where to activate capture
                (e.g., 0x5 = 0b0101 set core 0 and 2)
```

What is a core? I searched the documents, but couldn't find any explanation of which cores this is about and how selecting a coremask would effect the data I capture.

Thanks in advance.

**Comment by jlinktu** [comment]
Core means receive units here. If you have a device with four antennas, there should also be four cores. If your device has only one antenna then there is most likely only one core. The AC86U has four cores, the Nexus 6P has two cores, and the Nexus 5 and Raspberry Pi 3B+/4B have one core each. Indexing starts at core 0. With the mask you can select from what cores you want to extract CSI, of course you are limited to the cores available on your device.

You should use the Issues section of the [nexmon_csi](https://github.com/seemoo-lab/nexmon_csi) project to ask questions specific to the CSI extractor patch.

**Comment by zeroby0** [comment]
@jlinktu I see. Thanks! that clarified everything.

I opened the issue here by mistake, I had both the repositories open in adjacent tabs and created it here by accident. Thank you for the help :)
