### ISSUE TITLE
Android NDK version?

### ISSUE THREAD

**Issue by chrisk44** [seemoo-lab/nexmon#38]
I tried to compile the utilities on ubuntu, but I get compilation errors...

With r11c (the one you suggested on bcm-public to use) I get:
././../wireshark/wsutil/adler32.c:27:18: fatal error: glib.h: No such file or directory

and with r13b (latest) I get:
././../libnexio/local/armeabi/libnexio.a: error adding symbols: File in wrong format

What version are you using?

Edit: That's with `make` in /utilities.

**Comment by matthiasseemoo** [comment]
r11c is correct, however, I had to commit some more files. So just push and it should build. btw. you do not really need to build wireshark from source, as the app currently still relies on an older prebuild version of wireshark. Someone, would need to adapt the wireshark helper library to be able to work with the current wireshark sources.
