### ISSUE TITLE
make install-firmware failing on RPi

### ISSUE THREAD

**Issue by Ben-Lichtman** [seemoo-lab/nexmon#39]
I cloned the repo to desktop, and ran through all the instructions to install the firmware for bcm43438 onto the RPi. Everything was successful until the final step - make install-firmware when

> pi@raspberrypi:~/Desktop/nexmon/patches/bcm43438/7_45_41_26/nexmon $ sudo make install-firmware 
> Makefile:2: /firmwares/bcm43438/7_45_41_26/definitions.mk: No such file or directory
> make: *** No rule to make target '/firmwares/bcm43438/7_45_41_26/definitions.mk'.  Stop.

I'm not really sure where to go from here. Am I doing something wrong?

**Comment by bakashinji** [comment]
see #35

**Comment by Ben-Lichtman** [comment]
Awesome! fixed the issue
