### ISSUE TITLE
bcmdhd native monitor patch

### ISSUE THREAD

**Issue by SamuelNigga** [seemoo-lab/nexmon#402]
Hi dear @matthiasseemoo .
My device xperia z5 compact and it uses bcm43455 .
i wanna try also native monitor by using this patch: https://github.com/ruleh/misc/blob/master/monitor/bcmdhd_enable_monitor.patch

here is my device's kernel source:
https://github.com/LineageOS/android_kernel_sony_msm8994

so if i use bcmdhd monitor patch for my device (in kernel source dir 'patch bcmdhd_enable_monitor.patch') and compile kernel then flash image, the native monitor mode can work ? 
regards..

**Comment by einsteinov** [comment]
It's working on Nexus 6p.But injection not working.

**Comment by SamuelNigga** [comment]
> It's working on Nexus 6p.But injection not working.

what you mean by saying "its working" ?

**Comment by einsteinov** [comment]
native monitor  with ruleh patch.you must have kernel 3.10.73

**Comment by SamuelNigga** [comment]
> native monitor with ruleh patch.you must have kernel 3.10.73

i have 3.10.84, so if you press:

aireplay-ng -9 wlan0

what it say ?
