### ISSUE TITLE
Can't Install dhdutil

### ISSUE THREAD

**Issue by HFeustel** [seemoo-lab/nexmon#406]
OS: UBUNTU 16.04
I am trying to install the dhdutil, but I am running into the following error: 
![image](https://user-images.githubusercontent.com/38013222/82492784-c77efb00-9ab4-11ea-9835-7c39193357e8.png)

I am using NDK 11c, but it only comes in 64 bit. The /home/hunter/.../linux-x86 directory does not exist which explained the command not found error. There is a directory named  /home/hunter/.../linux-x86-64 that contains the rest of the file path needed so I changed the directory name and got the following error:
![image](https://user-images.githubusercontent.com/38013222/82493256-abc82480-9ab5-11ea-8232-98c53281ab15.png)
![image](https://user-images.githubusercontent.com/38013222/82493272-b1256f00-9ab5-11ea-99b4-1467a93f68f0.png)

I think this is because it is compiled for 64 bit, but is expecting 32 bit. Since NDK 11c is not available for 32 bit Linux are there any work arounds? Thanks!

**Comment by AsmitaJha08** [comment]
Hello @HFeustel 
I am having the same issue, were you able to find any work around this?

Thanks & Regards
Asmita
