### ISSUE TITLE
"Nexus 5" 1.Can't start monitoring mode: 2.How to use frame injection

### ISSUE THREAD

**Issue by YaohuaLee** [seemoo-lab/nexmon#408]
I have install nexmon and many tools from `utilities` into my Nexus5 .There are no problems during the install process. Use `LD_PRELOAD=libfakeioctl.so tcpdump -i wlan0 `is also no problem.
But I had the following problems:

1: After start root, I use the command `nexuti -Iwlan0 - m2` can't start monitor all the time, but I can successfully switch channels using `nexutil -k.`

2: I want to use my Nexus5 inject frame to Asus ac-86u（it‘s has been install the nexmon_csi). I have noticed some functions mentioned in the discussion area, such as `sendframe.c, injection.c ioctl.c  etc`.  But how can I use them? I mean to give some **specific steps**. I just touched on this field , and may not use them.

I hope someone can help me. Thank you very much！（^_^）

**Comment by 289536718** [comment]
i did not use frame injection.   My asus ac86u collects csi of my phone hotspot after specifying mac-address. When other phone visit me, new data frame will be generated

**Comment by YaohuaLee** [comment]
@289536718  
Thank you for your reply. I've tried to` ping` my `TP-link` and successfully captured CSI (although the capture rate is very slow), but I have some specific requirements to implement frame injection, I can't do it. Even now, I can't start monitor in Nexus 5.

**Comment by YaohuaLee** [comment]
Thank you for your reply. I've tried to `ping` my TP-link and successfully captured CSI (although the capture rate is very slow), but I have some specific requirements to implement frame injection, I can't do it. Even now, I can't start monitor in nexus 5.

**Comment by 289536718** [comment]
i haven't tried to start frame injection on nexus 5. Although i have been advised,i seldom touch Linux,so i can't be implemented.sorry

**Comment by mikeWangJC** [comment]
Got the same problem,
hope someone can help.
