### ISSUE TITLE
Nexmon directory typo

### ISSUE THREAD

**Issue by creepersbane** [seemoo-lab/nexmon#41]
When attempting to compile/make, I get:

/buildtools/ucode_extractor/ucodeext -r bcmdhd_sta.bin -b 0x2D830 -l 0x8B82 -o ucode.bin
make[3]: /buildtools/ucode_extractor/ucodeext: Command not found

The build command should be:

./buildtools/ucode_extractor/ucodeext -r bcmdhd_sta.bin -b 0x2D830 -l 0x8B82 -o ucode.bin
^
(Period goes there)

**Comment by matthiasseemoo** [comment]
i suppose you did not run "source setup_env.sh" before running make?

Am 12.02.2017 4:21 nachm. schrieb "creepersbane" <notifications@github.com>:

**Comment by creepersbane** [comment]
I ran it 5 times.

**Comment by bakashinji** [comment]
Did you use sudo to call make [won't work --> sudo su; source setup_env.sh etc]? And from where did you call make?

**Comment by creepersbane** [comment]
This no longer relevant since I no longer need to use Nexmon (sorry!)

**Comment by guilleeh90** [comment]
Try change the root directory with this code in terminal:

"sudo grep -rl '$(Q)$(NEXMON_ROOT)' | xargs sed -i s@'$(Q)$(NEXMON_ROOT)'@/home/pi/nexmon@g"

where /home/pi is your user directory. It runs for me.

**Comment by BenjaminUrquhart** [comment]
@guilleeh90 I'm not sure why you're commenting on a closed issue from 5 years ago but sure.
