### ISSUE TITLE
Is it compatable with Nexus 6P on Android 10 with LoS?

### ISSUE THREAD

**Issue by root3d1** [seemoo-lab/nexmon#420]
Hi,
I have a nexus 6P which i installed nethunter on over the android 10 with LoS setup. Will the drivers work with this version. Im not that technical with things like this and saw on the list the nexus 6p and saw android 8 comparability but not android 10!
I have tried to use the nexmon app to install the patched firmware but it does not work as i think android 10 system partition is read only.
Any clarity would be great thanks!

**Comment by TheMMcOfficial** [comment]
Check this:

https://gitlab.com/kalilinux/nethunter/build-scripts/kali-nethunter-devices/-/issues/236

**Comment by yesimxev** [comment]
Also https://forum.xda-developers.com/t/rom-official-kali-nethunter-for-the-huawei-nexus-6p-los17-1.4079087

Supported, but EAPOL packet is malformed

**Comment by TQMatvey** [comment]
> Also https://forum.xda-developers.com/t/rom-official-kali-nethunter-for-the-huawei-nexus-6p-los17-1.4079087
> 
> Supported, but EAPOL packet is malformed

mmm i tried on other android versions and i get malformed packets everywhere xD

**Comment by yesimxev** [comment]
Need to look into the driver or patches. The libs seem fine, I'm not an expert at it so it will take time. I also have limited time too
