### ISSUE TITLE
Add support for RPi Kernel 5.4.y

### ISSUE THREAD

**Issue by ecdye** [seemoo-lab/nexmon#423]
The latest update to the RPi Kernel switches to 5.4.y and that is not currently supported. Could support be added so that installation works properly on the latest kernel update?

**Comment by matthiasseemoo** [comment]
To answer your question, it should be techically possible to support the 5.4.y kernel. The limiting factor is always time.

**Comment by ecdye** [comment]
Well support is going to be broken on RPi's until support for the new kernel is added as 5.4.y is now being pushed to RPi's by default.

**Comment by JLP04** [comment]
I have the same issue.

**Comment by matthiasseemoo** [comment]
just take a look to the changes we made to the driver and adopt them for the driver in the new kernel.

**Comment by ecdye** [comment]
I simply don't have the time or experience to do that. I was simply trying to make this known to your team as it appeared as I was implementing a function in a project I am working on.

**Comment by jlinktu** [comment]
Added support for 5.4 https://github.com/seemoo-lab/nexmon/commit/83eeaadd97efb06c0885826efb772654c015918d
