### ISSUE TITLE
RPi3 /usr/bin/ld: cannot find -lnexio

### ISSUE THREAD

**Issue by erospalberti** [seemoo-lab/nexmon#43]
Hello, in this step

`Install nexutil: from the root directory of our repository switch to the nexutil folder: cd utilities/nexutil/. Compile and install nexutil: make && make install.`

i receive this error 

`root@raspberrypi:/home/pi/tools/nexmon/utilities/nexutil# make
gcc -static -o nexutil nexutil.c -DBUILD_ON_RPI -DVERSION=\"IT_VERSION\" -DUSE_NETLINK -I. -I../../patches/include -I../libnexio -L../libnexio/ -lnexio -I../libargp
/usr/bin/ld: impossibile trovare -lnexio
collect2: error: ld returned 1 exit status
Makefile:15: set di istruzioni per l'obiettivo "nexutil" non riuscito
make: *** [nexutil] Errore 1
root@raspberrypi:/home/pi/tools/nexmon/utilities/nexutil#
`

what i do?

thk

**Comment by matthiasseemoo** [comment]
build libnexio first.

Am 16.02.2017 11:37 vorm. schrieb "erospalberti" <notifications@github.com>:

**Comment by erospalberti** [comment]
Ok, sorry I didn't see the libnexio folder in utilities.

Now it work

Thank you very much.
