### ISSUE TITLE
Extract CSI and send packets simultaneously 

### ISSUE THREAD

**Issue by tomer-avrahami** [seemoo-lab/nexmon#430]
Hi,

First, thanks a lot for your work.
I want to build a setup of two devices which are able to communicate one with each other and to extract CSI data from those packets. Time between packets should be ~50ms. 
Do you think this setup possible using Raspberry PI hardware (any version)?
Do you have any recommendation how I can build this kind of setup?

I am currently working over Pi4B, Kernel 5.4.
I was not able to connect to a WiFi network while extracting CSI.

From what I understand from Nexmon documentation, it is not possible to inject packets over PI4\Pi3B+, while CSI extraction is not possible anymore using PI3B (which enables packets injection). Am I correct? 

Thanks,
Tomer

**Comment by tomer-avrahami** [comment]
For future readers - I was able both to inject and extract CSI from PI4 using kernel 5.4.

**Comment by Hodit01** [comment]
If you don't mind, could you tell me how?

**Comment by Arsering** [comment]
@tomer-avrahami Sir, Would you mind tell me how to inject and extract CSI from PI4 simultaneously?

**Comment by Arsering** [comment]
> For future readers - I was able both to inject and extract CSI from PI4 using kernel 5.4.
 Sir, Would you mind tell me how to inject and extract CSI from PI4 simultaneously?

**Comment by Arsering** [comment]
@tomer-avrahami  Sir, Would you mind tell me how to inject and extract CSI from PI4 simultaneously?
