### ISSUE TITLE
Build dir not found while patching   /lib/modules/5.4.51-v7+/build:

### ISSUE THREAD

**Issue by baldevbarrsiwal** [seemoo-lab/nexmon#441]
@matthiasseemoo 

Hi could anyone please help here . I'm getting this error while patching for RPi 3 B Plus -- bcm43455c0:

  
BUILDING DRIVER for kernel 5.4 brcmfmac_5.4.y-nexmon/brcmfmac.ko (details: log/driver.log)
make[1]: *** /lib/modules/5.4.51-v7+/build: No such file or directory.

There no such directory exists on this location

**Comment by tweigel-dev** [comment]
just update your kernel. with 
```
sudo apt upgrade 
sudo reboot
```
this fixed the issue a few days ago at my pi3+.
the make file should find the right path. it is caused by the uname -r command at the makefile which is searching for the right driver sorted by kernel version.

**Comment by baldevbarrsiwal** [comment]
Thank you
