### ISSUE TITLE
Kali Linux

### ISSUE THREAD

**Issue by Megaeloelo** [seemoo-lab/nexmon#45]
Hello,
How to compile it on kali? Because I can't use:
apt-get install raspberrypi-kernel-headers.

**Comment by lupeeumeeu** [comment]
Try using kalimon, it worked for me, it already have nexmon or the old one

**Comment by nethunteros** [comment]
https://build.nethunter.com/nexmon-pi-builds/

PI-0w and PI-3 builds for Kali with nexmon support.  Monitor mode can be started with monstart/monstop or nexutil.

**Comment by NoobieDog** [comment]
@nethunteros Cheers Binkybear, nice work

**Comment by Megaeloelo** [comment]
Thx for the info.
