### ISSUE TITLE
nexus 6p 

### ISSUE THREAD

**Issue by chrisonline909** [seemoo-lab/nexmon#46]
any chance to support firmware version 7.112.201.1 for the nexus 6p?

**Comment by matthiasseemoo** [comment]
Yes, if you are willing to find the relevant functions in the new firmware
version.

Am 24.02.2017 6:01 vorm. schrieb "Chris" <notifications@github.com>:

**Comment by chrisonline909** [comment]
Thanks for the quick reply, I'll will see what I can find. Vendor image NBD91K works fine

**Comment by matthiasseemoo** [comment]
I can also give you an introduction, just contact me by email.

Am 25.02.2017 2:49 vorm. schrieb "Chris" <notifications@github.com>:
