### ISSUE TITLE
How to use IDA Pro to analyze complete.bin and extract the address and structures？

### ISSUE THREAD

**Issue by Hodit01** [seemoo-lab/nexmon#462]
### (1)get complete.bin
I copied the [rom_extraction](https://github.com/seemoo-lab/nexmon/tree/master/patches/bcm43455c0/7_45_154/rom_extraction) to [nexmon/patches/bcm43455c0/7_45_189/](https://github.com/seemoo-lab/nexmon/tree/master/patches/bcm43455c0/7_45_189), after modifying the[ Makefile](https://github.com/seemoo-lab/nexmon/blob/master/patches/bcm43455c0/7_45_154/rom_extraction/Makefile), I got complete.bin.
![image](https://user-images.githubusercontent.com/32798330/106384875-36fd0680-6408-11eb-88fb-22fa1b72d981.png)

#### Step1
![Step 1](https://user-images.githubusercontent.com/32798330/106385089-5b0d1780-6409-11eb-8fcf-5975e1fb3d9c.png)
#### Step2
![Step 2](https://user-images.githubusercontent.com/32798330/106385289-8cd2ae00-640a-11eb-98fa-9fe728cfe57b.png)
#### Step3
![image](https://user-images.githubusercontent.com/32798330/106385899-7d089900-640d-11eb-9ba7-2b27540eb838.png)
**I want to find the loading address and extract the address and structures, but I don‘t know how to do.
Actually I am not familiar with IDApro**
### 2.How to extract the address and structures use IDA pro?
# Thanks in advance

**Comment by jlinktu** [comment]
Loading address is ```0x0```.
It seems you loaded the file correctly.
IDA might not correctly recognize all instructions from the beginning. E.g. the first four bytes are a ```b.w.``` instruction. One possibility is to fix this by hand. Rerunning autoanalysis after fixing some instructions is also worth a try. 
Depending on what you are going for it might help you to start by naming functions as defined in [wrapper.c](https://github.com/seemoo-lab/nexmon/blob/master/patches/common/wrapper.c) that are marked with ```CHIP_VER_BCM43455c0, FW_VER_7_45_189``` and ```CHIP_VER_BCM43455c0, FW_VER_ALL```.
