### ISSUE TITLE
How to deal  with the unexpected sine wave when sending a signal？

### ISSUE THREAD

**Issue by VIRUSOLDLIu** [seemoo-lab/nexmon#503]
Hi!
I am trying to use the following command to send a signal.
nexutil -s427 -b -l20 -vCFIAANwFAACV0AAAKAAAAAEAAAA=
Sometimes the command performances well. But sometimes, there will be a sine wave instead of what we want. After several attempts, it apears irregularly and commonly.
I wonder can I avoid this phenomenon？
I will post the normal signal I send and the unexpected sine wave below.

the normal signal:
![IMG_20211227_163522](https://user-images.githubusercontent.com/49874756/147453718-3cbac3d7-fb22-4ab6-abed-5ace70e38a31.jpg)

the sine wave:
![IMG_20211227_163533](https://user-images.githubusercontent.com/49874756/147453777-fd3b4474-fec0-40d7-af36-a6fac55d2720.jpg)

Thanks in advance!

**Comment by matthiasseemoo** [comment]
This is a bug and we do not exactly know why it occurs. It appears that it happens less often, when you are on a free wifi channel with no other traffic.
