### ISSUE TITLE
Compiling nexmon on a Pi Zero 2 W

### ISSUE THREAD

**Issue by aluminum-ice** [seemoo-lab/nexmon#560]
Hello, I am trying to compile nexmon directly on a Pi Zero 2 W as part of getting packet injections to work for pwnagotchi on the 2W. I can build most of nexmon but when I build the firmware patch in /patches/bcm43436b0/9_88_4_65/nexmon I get an error:

  COLLECTING STATISTICS read /home/pi/nexmon/STATISTICS.md for more information
  COMPILING src/version.c => obj/version.o (details: log/compiler.log)
  GENERATING LINKER FILE gen/nexmon.pre => gen/nexmon.ld
  GENERATING LINKER FILE gen/nexmon.pre => gen/flashpatches.ld
  LINKING OBJECTS => gen/patch.elf (details: log/linker.log, log/linker.err)
make: *** [Makefile:121: gen/patch.elf] Error 1

[compiler.log](https://github.com/seemoo-lab/nexmon/files/11007193/compiler.log)
[error.log](https://github.com/seemoo-lab/nexmon/files/11007194/error.log)
[linker-err.log](https://github.com/seemoo-lab/nexmon/files/11007196/linker-err.log)
[linker.log](https://github.com/seemoo-lab/nexmon/files/11007197/linker.log)

I've reviewed the log files but I frankly do not understand what the linker log files are trying to tell me (especially the error log file).

I've gotten pwnagotchi to work well on the [Pi Zero 2 W](https://github.com/aluminum-ice/pwnagotchi). This is the final step I think I need...

**Comment by wpa-2** [comment]
Following.

**Comment by wpa-2** [comment]
> .elf

You have any luck with this, nothing I tried has made a difference.
