### ISSUE TITLE
Raspberry Pi 2W Glibc 2.33

### ISSUE THREAD

**Issue by aluminum-ice** [seemoo-lab/nexmon#563]
I am trying to rebuild nexmon from source on a Pi Zero 2 W using my 1.6.2 fork of pwnagotchi. My fork works well on the 2 W except deauth attacks do not work. I suspect recompiling nexmon may resolve the issue. When I follow the instructions to build nexmon, building the patch for the 2 W throws a GLIBC error:

`BUILDING DRIVER for kernel 5.15 brcmfmac_5.15.y-nexmon/brcmfmac.ko (details: log/driver.log)
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Debian 11.2.0-19) 11.2.0
  You are using:           gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
scripts/basic/fixdep: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33’ not found (required by scripts/basic/fixdep)
make[2]: *** [scripts/Makefile.build:288: /home/pi/nexmon/patches/driver/brcmfmac_5.15.y-nexmon/fweh.o] Error 1
make[2]: *** Deleting file ‘/home/pi/nexmon/patches/driver/brcmfmac_5.15.y-nexmon/fweh.o’
make[2]: *** Waiting for unfinished jobs….
scripts/basic/fixdep: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33’ not found (required by scripts/basic/fixdep)
make[2]: *** [scripts/Makefile.build:288: /home/pi/nexmon/patches/driver/brcmfmac_5.15.y-nexmon/fwil.o] Error 1
make[2]: *** Deleting file ‘/home/pi/nexmon/patches/driver/brcmfmac_5.15.y-nexmon/fwil.o’
scripts/basic/fixdep: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33’ not found (required by scripts/basic/fixdep)
make[2]: *** [scripts/Makefile.build:288: /home/pi/nexmon/patches/driver/brcmfmac_5.15.y-nexmon/chip.o] Error 1
make[2]: *** Deleting file ‘/home/pi/nexmon/patches/driver/brcmfmac_5.15.y-nexmon/chip.o’
scripts/basic/fixdep: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33’ not found (required by scripts/basic/fixdep)
make[2]: *** [scripts/Makefile.build:288: /home/pi/nexmon/patches/driver/brcmfmac_5.15.y-nexmon/cfg80211.o] Error 1
make[2]: *** Deleting file ‘/home/pi/nexmon/patches/driver/brcmfmac_5.15.y-nexmon/cfg80211.o’
make[1]: *** [Makefile:1868: /home/pi/nexmon/patches/driver/brcmfmac_5.15.y-nexmon] Error 2
make: *** [Makefile:50: brcmfmac.ko] Error 2`

Has anyone run into this problem? Any hints on how to resolve it? I'm not familiar with this issue so it's a learning curve. If anyone can point me to useful documentation, I'd appreciate it.

**Comment by TQMatvey** [comment]
how exactly did you fix this?
