### ISSUE TITLE
Recommended samsung phone

### ISSUE THREAD

**Issue by tomer-avrahami** [seemoo-lab/nexmon#567]
Hi,

Which Samsung phone version is the most recommneded for packet injection project?

Thanks,
Tomer

**Comment by davidrozen76** [comment]
Nexmon is supported on Samsung Galaxy S7, S10, S20 and S21 FE. I suppose S20's and S21's hardware is better than older devices which might yield better results.

**Comment by tomer-avrahami** [comment]
Thanks!
Is it possible to consult with you privately?
If so, this is my mail:
tomer.avrahami@wiliot.com

**Comment by savox-326** [comment]
@davidrozen76 could you tell how actions you made for launch monitor? Simple bcm wifi firmware replacing not helpful for my device (Note 20 Ultra, Snapdragon)

**Comment by savox-326** [comment]
@davidrozen76 can you give me your s21fe's wifi firmware? My compiled one no has wlc_monitor_attach function name checked with strings | grep
