### ISSUE TITLE
August 30 2023 Commits Cause Errors

### ISSUE THREAD

**Issue by aluminum-ice** [seemoo-lab/nexmon#573]
@jlinktu

2f14bdfb288022e500b82c21cfabec2241d75c04 These recent commits are causing a compilation error when compiling nexmon for the Raspberry Pi boards.

**Comment by jlinktu** [comment]
The earliest I can fix is in three days, please revert back locally until then.
Can you give me more details on what step is failing?

**Comment by jlinktu** [comment]
76b1edcbd5eb07ef65fd4723be1e75c2734d0fbb should fix it, please confirm

**Comment by savox-326** [comment]
@jlinktu sorry for disturbing in another theme branch but don't know when will I "get" you to answer. So when the full patch for bcm4375 will be released?

**Comment by DrSchottky** [comment]
Just stepping in to ask @jlinktu if the bcm43439a0 support is still WIP (I'm working on the driver side to get a console dump, but I'll stop here if it's something already done and just waiting to be committed)

**Comment by jlinktu** [comment]
I have a working example for dumping the console, but haven't decided on how to integrate the pico w stuff into nexmon yet. Maybe I put it into a different repo.
I'll speed up deciding, now that I know that there is interest in it.

**Comment by jlinktu** [comment]
There are a couple of reasons that might trigger the error message "brcmfmac: brcmf_cfg80211_nexmon_set_channel: Set Channel failed".
There should be an error code reported together with the given message which might tell you more about the reason why the channel could not be set. Failing to set the channel should not crash the driver, therefore this can be seen to be more of a warning than an error message.

**Comment by jlinktu** [comment]
In this case you can lookup the error code in [include/uapi/asm-generic/errno.h](https://github.com/torvalds/linux/blob/65d6e954e37872fd9afb5ef3fc0481bb3c2f20f4/include/uapi/asm-generic/errno.h#L93). `110` is the value defined by `ETIMEDOUT`. The origin of the error in your case is probably a timeout in `brcmf_sdio_bus_txctl`, which might mean the interface/bus is down.
Things to look out for:
- Are you using matching versions for driver, kernel, and firmware? If you are on kernel >= 6, @DrSchottky provides a recent `brcmfmac` with his #pull request #561.
- Is `wpa_supplicant` interfering?
- Did you forget to bring up the interface after replacing the driver?
- Did the chip come up but then crashes? Check dmesg for hints.

**Comment by DrSchottky** [comment]
> Are you using matching versions for driver, kernel, and firmware? If you are on kernel >= 6, @DrSchottky provides a recent `brcmfmac` with his [Add brcmfmac for Kernel 6.1.y #561](https://github.com/seemoo-lab/nexmon/pull/561) .

About that: any chance it will be merged sooner or later? On my fork I have multiple fixes/improvements that would be nice to upstream.

**Comment by jlinktu** [comment]
Yes, I can check and merge soon.

**Comment by jlinktu** [comment]
@DrSchottky A bit more delayed than I had in mind but you can find the Pico W stuff now here: https://github.com/seemoo-lab/pico-nexmon.git

**Comment by DrSchottky** [comment]
@jlinktu that's great!
I should still have the driver patches for monitor mode, 
I'll try to find the time to send some contributions over the weekend
