### ISSUE TITLE
About qca9500(TP-Link Talon AD7200)

### ISSUE THREAD

**Issue by maple-42** [seemoo-lab/nexmon#612]
I am following the quick guide(https://seemoo-lab.github.io/talon-tools/GettingStarted.html) of the tool to set it up, but there are many things I don't understand, so I would like to ask a question.

I was successful in flashing to one device per the instructions.
However, I get the following error in the subsequent ssh connection(ssh 192.168.0.1)part.
I am sorry to bother you, but I would appreciate it if you could help me when you have time.

ssh root@192.168.0.1
PTY allocation request failed on channel 0
shell request failed on channel 0

**Comment by jlinktu** [comment]
Not related to this repository.

If at all, this would have to go to [https://github.com/seemoo-lab/talon-tools](https://github.com/seemoo-lab/talon-tools). However, the creators of `talon-tools` are no longer at the Secure Mobile Networking Lab, thus, no answer guaranteed.

Apart from this, I would suggest you to consult a web search engine of your choice as this seems to be rather a generic problem than being specific to `talon-tools` or `nexmon`.

Closing the issue as not related.
