### ISSUE TITLE
pixel 8

### ISSUE THREAD

**Issue by Tenroh** [seemoo-lab/nexmon#614]
Hello everyone,

I have a Pixel 8 and a Pixel 8 Pro, and I have noticed that work has started on enabling monitor mode on the BCM4398D0 WiFi chip. To advance in this effort, I'm trying to decompile the firmware ( fw_bcmdhd.bin_4398_d0 ) using IDA Pro 7.7, but I'm not able to get a correct decompilation.
Is IDA Pro 7.7 the appropriate version for decompiling this firmware?
Are there any other software tools that you would recommend for this task?
I would greatly appreciate any advice or suggestions you can offer.

Thank you in advance for your help!

Best regards,

**Comment by jlinktu** [comment]
Any version of any reversing tool, including IDA Pro 7.7, that supports armv7a disassembling and creation of pseudo-decompilation code is fine.

Our current state on this might not always be represented by the state of this repository. If you really need monitor mode on the Pixel 8 phones, you can contact me via email and we might find a solution.
