### ISSUE TITLE
EXTRACTING UCODE ERR: ram file empty or unavailable. make[3]: *** [Makefile:17: ucode.bin] Error 1 make[3]

### ISSUE THREAD

**Issue by mrsaad381** [seemoo-lab/nexmon#620]
Here is my script which i run 
sudo su

apt-get update && apt-get upgrade

Install the kernel headers and dependencies
sudo apt install raspberrypi-kernel-headers git libgmp3-dev gawk qpdf bison flex make autoconf libtool texinfo

 Clone the nexmon repository
git clone https://github.com/seemoo-lab/nexmon.git

Go into the root directory of the repository
cd nexmon

For 64-bit Raspberry Pi OS, execute the following commands
sudo dpkg --add-architecture armhf
sudo apt-get update
sudo apt-get install libc6:armhf libisl23:armhf libmpfr6:armhf libmpc3:armhf libstdc++6:armhf
sudo ln -s /usr/lib/arm-linux-gnueabihf/libisl.so.23.0.0 /usr/lib/arm-linux-gnueabihf/libisl.so.10
sudo ln -s /usr/lib/arm-linux-gnueabihf/libmpfr.so.6.1.0 /usr/lib/arm-linux-gnueabihf/libmpfr.so.4

in root directory  Setup the build environment
source setup_env.sh

 Compile some build tools and extract the ucode and flashpatches from the original firmware files
make

when i enter make its give me this error 
Here;s Error

  EXECUTING MAKE FOR FIRMWARE VERSION 7_95_49_2271bb6/
make[3]: Entering directory '/home/raspberrypi/nexmon/firmwares/bcm43439a0/7_95_49_2271bb6'
  EXTRACTING UCODE
ERR: ram file empty or unavailable.
make[3]: *** [Makefile:17: ucode.bin] Error 1
make[3]: Leaving directory '/home/raspberrypi/nexmon/firmwares/bcm43439a0/7_95_49_2271bb6'
make[2]: *** [Makefile:8: 7_95_49_2271bb6/] Error 2
make[2]: Leaving directory '/home/raspberrypi/nexmon/firmwares/bcm43439a0'
make[1]: *** [Makefile:7: bcm43439a0/] Error 2
make[1]: Leaving directory '/home/raspberrypi/nexmon/firmwares'
make: *** [Makefile:5: firmwares] Error 2

i see all issues but not found any help and i didnt found ucod.bin file in directory 

i am installing it on resberry pi 64 bit with kernel version
raspberrypi@raspberrypi:~/nexmon $ uname -r
6.6.31+rpt-rpi-v8

please i need urgent help

**Comment by jlinktu** [comment]
See https://github.com/seemoo-lab/nexmon/issues/578
