### ISSUE TITLE
Trying to install on fresh RPI OS

### ISSUE THREAD

**Issue by renewedbullet** [seemoo-lab/nexmon#635]
Followed the Steps multiple times doesn't seem to work anymore. 

Was able to compile with DrSchottkys repo but other issues happen with that repo wanted to try the original but following the instructions posted I get this error, 
root@raspberrypi:/home/pi/nexmon/patches/bcm43455c0/7_45_206/nexmon# make

          ###########   ###########   ##########    ##########
         ############  ############  ############  ############
         ##            ##            ##   ##   ##  ##        ##
         ##            ##            ##   ##   ##  ##        ##
         ###########   ####  ######  ##   ##   ##  ##    ######
          ###########  ####  #       ##   ##   ##  ##    #    #
                   ##  ##    ######  ##   ##   ##  ##    #    #
                   ##  ##    #       ##   ##   ##  ##    #    #
         ############  ##### ######  ##   ##   ##  ##### ######
         ###########    ###########  ##   ##   ##   ##########

            S E C U R E   M O B I L E   N E T W O R K I N G

                               presents:

              # ###   ###  #   # # ###  ###   ###  # ###
              ##   # #   #  # #  ##   ##   # #   # ##   #
              #    # #####   #   #    #    # #   # #    #
              #    # #      # #  #    #    # #   # #    #
              #    #  #### #   # #    #    #  ###  #    #

                The C-based Firmware Patching Framework

                           !!! WARNING !!!
    Our software may damage your hardware and may void your hardware’s
     warranty! You use our tools at your own risk and responsibility

  COLLECTING STATISTICS read /home/pi/nexmon/STATISTICS.md for more information
  COMPILING src/console.c => obj/console.o (details: log/compiler.log)
/home/pi/nexmon/buildtools/gcc-arm-none-eabi-5_4-2016q2-linux-armv7l/bin/arm-none-eabi-gcc: error while loading shared libraries: libm.so.6: ELF load command address/offset not page-aligned
make: *** [Makefile:65: obj/console.o] Error 127

**Comment by jlinktu** [comment]
> `libm.so.6: ELF load command address/offset not page-aligned`

Seems to be related to 16k paging on the Raspberry Pi 5, if you don't explicitly need this you can go with 8k pages by adding `kernel=kernel8.img` to your `/boot/firmware/config.txt` file.

**Comment by renewedbullet** [comment]
still encountering same issue any suggestions? 
![image](https://github.com/user-attachments/assets/15f186fc-0ac8-4b62-9743-1bc57d7dc46f)

**Comment by jlinktu** [comment]
Search the issues for "`libisl.so`".
