### ISSUE TITLE
Can it work on older Android Version?

### ISSUE THREAD

**Issue by pacau999** [seemoo-lab/nexmon#78]
I tried to make it backard compatible to android 2.3.6, kitkat, but without succes. IS it possible?
I have an galaxy Y that have BCM4330, and it is my unique chance to make monitor mode works
Thank you, have a nice day!

**Comment by matthiasseemoo** [comment]
The firmware patch and the binaries should work. The app might be harder to port to an older version. Maybe you can find a custom ROM based at least on Android Marshmallow for your device.

**Comment by mirzaatifbaig** [comment]
Nope.It Doesn't work on earlier models.Turns out the least Very should be 6.0
