### ISSUE TITLE
Connecting to an access point with the modified driver.

### ISSUE THREAD

**Issue by nikilp** [seemoo-lab/nexmon#84]
I want to use the modified driver to connect to an access point. The instructions say:
> **Note:** It is possible to connect to an access point using our modified driver and firmware, just set the wireless interface in Managed mode.

But when I set the wlan0 to managed mode (nexutil -m0), clicking the network interfaces icon in the top right gives me:
"No wireless interfaces found"
and the tooltip is:
"wlan0: Associated with
 wlan0 Configured 169.254.72.196/16"

Did anyone manage to connect with the modified driver to an access point?

**Comment by lupeeumeeu** [comment]
did you remove wpasupplicant??don't do that if still want to use in managed mode, here i could switch easily

**Comment by nikilp** [comment]
True. That was the issue. Thanks.
